spring:
  application:
    name: MovieAPI

  datasource:
    driver-class-name: org.postgresql.Driver
    username: spring
    password: ruby1234
    url: jdbc:postgresql://localhost:5432/movieapi

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.ethereal.email
    port: 587
    username: "triston20@ethereal.email"
    password: "QTMaFs4w9Qc2ycg3Vt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Project Environment Variable
project:
  poster_path: posters/

base:
  url: "http://localhost:8080/api/v1"

frontend:
  url: "https://localhost:5437/reset-password"

jwt:
  secretKey: "RDl4S211R3lYbDFYNUI2Yk9KV1ZxaGc1SUtDM0N2OEc="
  accessToken: 900000
  refreshToken: 86400000